global:
  scrape_interval: 5s
  evaluation_interval: 5s

scrape_configs:
  - job_name: "gateway"
    metrics_path: "/metrics"
    static_configs:
      - targets: ["gateway:8000"]

  - job_name: "auth"
    metrics_path: "/metrics"
    static_configs:
      - targets: ["auth:8001"]

  - job_name: "employee"
    metrics_path: "/metrics"
    static_configs:
      - targets: ["employee:8002"]

  - job_name: "leave"
    metrics_path: "/metrics"
    static_configs:
      - targets: ["leave:8003"]

  - job_name: "payroll"
    metrics_path: "/metrics"
    static_configs:
      - targets: ["payroll:8004"]

  - job_name: "notification"
    metrics_path: "/metrics"
    static_configs:
      - targets: ["notification:8005"]
